language: node_js
node_js:
- node
services:
- docker
before_script:
- npm install grunt-cli -g
script:
- docker build -t patrikx3/lede-insomnia .
env:
  global:
    secure: z1eH2cQ/APEwYxDhmSYQXkq8tCCir50oZQy2DKvOwik4JKYrI5Tm3yJGyRSjrqiquM/lMnS8GNna6RmFhVT7oOhx5N93vjHZGxjSnz63e72zdAe8uFazzXXGfQ2NTP4/lH6B0UKEIfNJl08qpu8bXx0+JDeNTUCgbBaeUulxBFqqgs8r5ICKTTK+ITv7jTyLssnwwHF23ycW+xvpewpLuP2EAlVRqesIXAC74SmLfEOzEazi+XY8KPheExfSrY7XPjXCA56elkz+RXOYekcS7eXRhtGkF29BOh8V88PQxXuhzGaV+UdsFhKI8a5Pfj9UhCOrWGK5kvV2J5uayaTVLw6iQwNMN3u2d/w0UGrwYY1NkM5j0Iuden8qWXxFt89k/lRLtgl9T+9PoaRutJ3YBTeQ38xlUKeXGmlfSEUUgKNLQlmWO83V98iGbNf7M/x6Abj3t49jgKSwczczveIVu1r51D9DX7YogxwSf3XC5MICruTJ47K1992uWIoTkW2qMvWKF6ErOiBex4l71/+V+dQ0IQ3rCvIDkckqUKNjFBsQ2C+QwPoDMdsxggD1gQ8RoXMYC3rM+LjlgX53xINORCksr5WdRR+gx8piLpcmu6OcCQRo0hFpIgPGSnjsNVW5Mzvu/Q4ENqEbVOkLO9rzzGggHi/akE7tMd9kZOToCaQ=
