#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
docker run -v $DIR/secure:/build/secure -v $DIR/patches:/build/patches -v $DIR/secure:/build/secure -v $DIR/make-scripts:/build/make-scripts -v $DIR/router:/build/router -v $DIR/image-builder-files:/build/image-builder-files -t -i patrikx3/lede-insomnia:linksys-wrt bash