#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

patches-and-feeds() {
    rsync -vr /build/patches/source /build
}

feeds() {
    rsync -vr /build/patches/source/feeds /build/source
}

setup-config() {
    rsync -vr /build/router/$1/source/. /build/source
    touch .config
    make -j1 V=s
}

setup-image-builder() {
    rsync -vr /build/router/$1/image-builder/. /build/$2
    popd /build/$2
    touch .config
    # make image "$(< file.txt)"
    # make -j9 image PROFILE=dir-860l-b1 PACKAGES="opkg-list-installed.txt"
    #make -j9 image PROFILE=$1 PACKAGES="$(< /build/router/$1/opkg-list-installed.txt )"

}

export -f patches-and-feeds
export -f feeds
export -f setup-config
