#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $DIR/lib

patches-and-feeds
setup-config "linksys-3200acm-and-linksys-wrt3200acm-eduperez-mwlwifi"
#"lede-imagebuilder-17.01.2-mvebu.Linux-x86_64"