#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $DIR/lede-insomnia-lib

ROUTER_PROFILE="linksys-wrt3200acm"
ROUTER_TARGET="mvebu"
ROUTER_SUB_TARGER="generic"
FIRMWARE_NAME="insomnia-eduperez-mwlwifi"
IMAGE_BUILDER_FILE="/build/source/bin/targets/${ROUTER_TARGET}/${ROUTER_SUB_TARGER}/lede-imagebuilder-${LEDE_VERSION_TOTAL}-${ROUTER_TARGET}.Linux-x86_64.tar.xz"

patches-and-feeds
setup-config-and-build $ROUTER_PROFILE $1
setup-image-builder-and-build $IMAGE_BUILDER_FILE $ROUTER_PROFILE $FIRMWARE_NAME $1
post-build