#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $DIR/lede-insomnia-lib

ROUTER_NAME="d-link-dir-860l-b1"
ROUTER_PROFILE="dir-860l-b1"
ROUTER_TARGET="ramips"
ROUTER_SUB_TARGER="mt7621"
IMAGE_BUILDER_FILE="/build/source/bin/targets/${ROUTER_TARGET}/${ROUTER_SUB_TARGER}/lede-imagebuilder-${LEDE_VERSION_TOTAL}-${ROUTER_TARGET}-${ROUTER_SUB_TARGER}.Linux-x86_64.tar.xz"

IMAGE_BUILDER_PATH=$(image-builder-uncompress $IMAGE_BUILDER_FILE)

echo $IMAGE_BUILDER_PATH
pushd $IMAGE_BUILDER_PATH
#rsync -vr /build/router/$ROUTER_NAME/image-builder/. /build/$(basename $IMAGE_BUILDER_PATH)
make image PROFILE=$ROUTER_PROFILE PACKAGES="$(< /build/router/${ROUTER_NAME}/opkg-list-installed.txt)"
popd
